data = [
    ("Orange","Sweet orange fruit,citrus fruit"),
    ("Apple","Red fruit, good for making cider"),
    ("Lemon","Sour,yellow citrus fruit"),
    ("Grape","small,sweet,grows in bunch"),
    ("Melon","Sweet and juicy")
]

print(ord("A")) #prints unicode of A

def simpleHash(X:str)->int:
    basicHash = ord(X[0])      #X[0] returns the first character of value of X
    return(basicHash%10)       #%10 to get result from 0 to 9

for key,value in data:
    h = simpleHash(key)
    print(f"{key}:{h}")

print("Python's Hash value")

for key,value in data:
    h = hash(key)           #hash() returns hash value of a char generated by python 
    print(f"{key}:{h}")


